<?php

namespace AppBundle\Repository;

/**
 * CatlistingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatlistingRepository extends \Doctrine\ORM\EntityRepository
{
}
